
@url=http://localhost:3002
@json=Content-Type:application/json
Bearer + 空格 是为了规范
@token=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMDQ4MGZjNmU1NDg0NGY0NDMyZjQ3YyIsImlhdCI6MTU3NzM3MjcyNn0.WKIkO3xFOTgE-ZG7xP8unR8MN8lz7e7a0f4axd0Kqg4
###
get {{url}}


###注册
post {{url}}/register
{{json}}

{
    "username":"seaton4",
    "password":"123456"
}


### 登陆
post {{url}}/login
{{json}}

{
    "username":"seaton3",
    "password":"123456"
}

###查看所有用户
get {{url}}/user/list
{{token}}

###查看某个用户的信息
get {{url}}/user/profile
{{token}}

### 新闻-新增
post {{url}}/news
{{json}}
{{token}}

{
    "title":"新闻标题2",
    "type":"css类",
    "content":"<p>这是内容</p>"
}

### 新闻-修改
put {{url}}/news/5e0aa61cfce0fc1098b96226
{{json}}
{{token}}

{
    "title":"新闻标题2",
    "type":"css类",
    "content":"<p>这是内容2</p>"
}


### 新闻-删除
delete {{url}}/news/5e0aa61cfce0fc1098b96226
{{token}}


### 新闻-查询-列表
get {{url}}/news
{{token}}

### 新闻-查询-详情
get {{url}}/news/5e0aa61cfce0fc1098b96226
{{token}}